### ISSUE TITLE
Error with full text native

### ISSUE THREAD

**Issue by rmcgirr83** [phpbb/quickinstall#102]
On fresh install of 3.2.5

Fatal error: Uncaught Error: Call to a member function trigger_event() on null in F:\xampp7\htdocs\qi\sources\phpBB3_alt\phpBB325\phpbb\search\fulltext_native.php:1466 Stack trace: #0 F:\xampp7\htdocs\qi\modules\qi_create.php(574): phpbb\search\fulltext_native->index('post', '1', 'This is an exam...', 'Welcome to phpB...', '2', '2') #1 F:\xampp7\htdocs\qi\includes\functions_module.php(52): qi_create->__construct() #2 F:\xampp7\htdocs\qi\index.php(296): module_handler->load('create', 'qi_main') #3 {main} thrown in F:\xampp7\htdocs\qi\sources\phpBB3_alt\phpBB325\phpbb\search\fulltext_native.php on line 1466

**Comment by VSEphpbb** [comment]
Can you explore further. I can't reproduce this error with 3.2.5.

**Comment by VSEphpbb** [comment]
@rmcgirr83 try with the new version 1.3.4

Seems your QI is pretty outdated.

**Comment by rmcgirr83** [comment]
Yes indeed, didn't realize it was that outdated.  Thanks Matt.
