### ISSUE TITLE
Creating a phpBB 3.3.1 board on QI 1.5.0 with php >7.2 fails

### ISSUE THREAD

**Issue by warmweer** [phpbb/quickinstall#157]
QI starts up seemingly without problems but  when starting the creation of a 3.3.1 board it errors out.
Standard creation of a 3.3.1 board using the phpBB install interface works without any problem
Tried with USBWebserver 8.6.5 (php 7.4.3) and Wampserver (php 7.3.21 and 7.4.9)

example of error message:
Fatal error: Uncaught Error: Call to undefined function can_load_dll() in E:\USBW74\root\QI\modules\qi_create.php:403 Stack trace: #0 E:\USBW74\root\QI\includes\functions_module.php(52): qi_create->__construct() #1 E:\USBW74\root\QI\index.php(248): module_handler->load('create', 'qi_main') #2 {main} thrown in E:\USBW74\root\QI\modules\qi_create.php on line 403

Edit: reinstalled Wampserver and now  creation of a 331 board with php 7.3.21 work flawlessly (with MySQL 8.0.21 - still needs further testing as I forgot to install earlier version of MySQL

**Comment by iMattPro** [comment]
In your PHP Info do you have GD Support enabled?

**Comment by warmweer** [comment]
> In your PHP Info do you have GD Support enabled?
php 7.4.3 (installing phpBB 3.3.1 succeeds as standalone, but not with QI 150
extension=php_gd2.dll  in php.ini (Windows system) (the ; was already removed)

php info doesn't mention anything about GD (searched using phpinfo()  on the PHP information page in a non QI installed phpBB)

with php7.1.11 ( installing phpBB succeeds with QI 150and without QI 150)
extension=php_gd2.dll  in php.ini (Windows system) (the ; was already removed)
phpinfo()

GD Support | enabled
-- | --
GD Version | bundled (2.1.0 compatible)
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.8.0
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 9 compatible
PNG Support | enabled
libPNG Version | 1.6.34
WBMP Support | enabled
XPM Support | enabled
libXpm Version | 30512
XBM Support | enabled
WebP Support | enabled

**Comment by iMattPro** [comment]
The board that was created is irrelevant. Use QuickInstall's PHP Info tab. Either way doesn't matter. In your first encounter you did not have GD support for some reason so you encountered a non existing piece of code somebody copy-pasted from phpBB 3.0. That's gonna be trashed now though so that won't happen again.

**Comment by warmweer** [comment]
Strange that this wasn't encountered (or reported) by other QI users.
BTW confirmed with the QI phpinfo, on php 7.4.3 no GD, on 7.1.11 there is GD

**Comment by iMattPro** [comment]
Fixed #158
