### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by nomind60s** [phpbb/quickinstall#160]
Because I'm an early adopter I'm trying this out on a CentOS Linux release 7.9.2009 (Core) server that has PHP 8.0.2 installed via https://rpms.remirepo.net/wizard/

php -v shows:
```
PHP 8.0.2 (cli) (built: Feb  2 2021 19:28:42) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
```

QuickInstall installed properly and generally seems to work with PHP 8 but I'm running into one PHP Warning consistently. 

`[QI Debug] PHP Warning: in file /var/www/html/qi/includes/settings.php on line 144: Undefined array key "no_dbpasswd"`

I can use QI to create a phpBB 3.3.3 board but it won't redirect to the board, the error is:
```
[QI Debug] PHP Warning: in file /var/www/html/qi/includes/settings.php on line 144: Undefined array key "no_dbpasswd"
{"redirect":"boards\/Test\/"}
```
If I reload the QI main page I can see the new board and the link to it works. Deleting the board also works.

Otherwise so far so good.

**Comment by 3D-I** [comment]
I do not have the same issue.
![immagine](https://user-images.githubusercontent.com/480857/107271085-07737d00-6a4c-11eb-82b6-22f91ee77780.png)

**Comment by 3D-I** [comment]
Okay I see. I do not have it set (no value), I will check it later on.

**Comment by iMattPro** [comment]
Will already be fixed in the next release
