### ISSUE TITLE
Additional board config settings

### ISSUE THREAD

**Issue by 3D-I** [phpbb/quickinstall#182]
Latest master branch in use here
---

Only the first entry is working.

I used
```
session_length;888888
load_birthdays;0
```
and the last line is being ignored.

![image](https://user-images.githubusercontent.com/480857/120869069-d50b0400-c595-11eb-9a82-f1b51d2b2b8b.png)
---
![image](https://user-images.githubusercontent.com/480857/120869137-01bf1b80-c596-11eb-81f6-14a74982a465.png)

**Comment by iMattPro** [comment]
Fixed here https://github.com/phpbb/quickinstall/pull/183/commits/c7d5cea628b6e3b73fba2302e0f12ba541a958e4
