### ISSUE TITLE
phpBB 3.2.11 and PHP 7.2.34 install goes in loop forever.

### ISSUE THREAD

**Issue by 3D-I** [phpbb/quickinstall#185]
Using the master branch.

---

Attempting to install phpBB  3.2.11 with PHP 7.2.34.

After 10 minutes _(with win10-64 and SSD HD)_ still keeps loading something, no error logs.

![image](https://user-images.githubusercontent.com/480857/122129510-79af0080-ce36-11eb-87cf-8d2bf477df7f.png)

**Comment by 3D-I** [comment]
Ok, got the issue.
If you leave blank the `Board database and directory name:`

![image](https://user-images.githubusercontent.com/480857/122129939-24272380-ce37-11eb-9334-c177abf626e4.png)

Then it goes in loop without any error thrown.

**Comment by iMattPro** [comment]
You'll have to look into that further on your end. Javascript is not working on your end. As I've never been able to reproduce that. You always get an error message if you ever try to create a board without setting that name field.

**Comment by 3D-I** [comment]
Let this open please. I will do some further test tomorrow.

**Comment by iMattPro** [comment]
Disable JavaScript and try again leaving the field blank and see what sort of error or feedback you get too.

**Comment by 3D-I** [comment]
Okay, it is 06:03 here. I will do tomorrow and report.

**Comment by 3D-I** [comment]
Okay, I tried to reply the issue to no success. Therefore I am closing this issue. Thx.

![image](https://user-images.githubusercontent.com/480857/122156627-a3cde600-ce69-11eb-9f5b-3ae1981daf87.png)

**Comment by iMattPro** [comment]
When I tried it with 3.2.11 and 7.2.34 I get (PHP and phpBB versions shouldn't matter though):
1. Under normal conditions, the expected JS form validation error:
<img width="246" alt="Screen Shot 2021-06-15 at 9 05 38 PM" src="https://user-images.githubusercontent.com/303711/122156233-71969700-ce1d-11eb-88e8-25a6686d53b3.png">

2. With JS disabled, the expected PHP generated error page:
<img width="267" alt="Screen Shot 2021-06-15 at 9 06 51 PM" src="https://user-images.githubusercontent.com/303711/122156346-a571bc80-ce1d-11eb-9e7a-9be0dc7e8b62.png">

3. Hacking it to bypass the form validation gives the expected JS error immediately as well 
<img width="321" alt="Screen Shot 2021-06-15 at 9 09 17 PM" src="https://user-images.githubusercontent.com/303711/122156505-f5e91a00-ce1d-11eb-8c9c-ed116c961875.png">

So I'm unable to reproduce.

**Comment by 3D-I** [comment]
See my above 👍🏼
