### ISSUE TITLE
incorrect "Script path" in "Server settings"

### ISSUE THREAD

**Issue by Skouat** [phpbb/quickinstall#43]
Hi tumba,

In ACP >> General >> Server settings, there is a double ```/``` at the beginning of the script path.
eg : ```//boards/testing``` instead of ```/boards/testing```

**Comment by tumba25** [comment]
Not here. IIRC you have "http://localhost/boards/", right?

**Comment by Skouat** [comment]
Yes QI is installed on the root of my local webserver.

It remember me the bug [EXTTOOLS-655](https://github.com/phpbb/quickinstall/commit/67d99c9a1483cec743a227cb23eadc8e178404ac).

**Comment by tumba25** [comment]
I am not able to reproduce this. Are you using the latest dev version in the repo? If you are I'd like a copy of your config/profile file.

**Comment by Skouat** [comment]
There is no problem with "script path" if I put QI under a subfolder (eg : htdocs/qi/)

Yes I use the lastest dev version.

My main profile:
```
admin_email=qi_admin@phpbb-quickinstall.tld
admin_name=Skouat
admin_pass=password
alt_env=
automod=1
board_email=qi_admin@phpbb-quickinstall.tld
boards_dir=boards/
boards_url=boards/
cache_dir=cache/
chunk_post=1000
chunk_topic=2000
chunk_user=5000
cookie_domain=
cookie_secure=0
create_admin=1
create_mod=1
db_prefix=qi_
dbhost=localhost
dbms=mysqli
dbpasswd=password
dbport=
dbuser=root
default_lang=fr
default_style=
delete_files=1
drop_db=1
email_domain=phpbb-quickinstall.tld
email_enable=1
grant_permissions=
install_styles=0
make_writable=0
no_dbpasswd=0
num_cats=2
num_forums=10
num_new_group=10
num_replies_max=50
num_replies_min=0
num_topics_max=25
num_topics_min=5
num_users=100
other_config=
populate=0
qi_lang=fr
qi_tz=UTC
redirect=1
server_name=localhost
server_port=80
show_confirm=0
site_desc=eviLs testing hood
site_name=Testing Board
smtp_auth=PLAIN
smtp_delivery=0
smtp_host=
smtp_pass=
smtp_port=25
smtp_user=
table_prefix=phpbb_
```

Off topic:
Does it normal that the "Cookie domain" setting is empty?
![qi_cookie_domain](https://cloud.githubusercontent.com/assets/416780/6026271/c0987796-abd9-11e4-8d15-ff73a1422c20.png)

**Comment by Skouat** [comment]
Feedback after some investigations...
In the DB, the config_value of "script_path" is equal to `\/boards/testboard/`
If I remove the chars `\` and purge the cache of phpBB, the script_path is correct.

When QI is installed on the root of the webserver, before the code execution of the [line 317](https://github.com/phpbb/quickinstall/blob/master/modules/qi_create.php#L317) `$script_path` has the value `/index.php`, after the code execution of the [line 317](https://github.com/phpbb/quickinstall/blob/master/modules/qi_create.php#L317), `$script_path` takes the value `\`

I've tested to switch the line 316 with the line 317, and it seems that it solves this issue.
But I'm not sure that is the right fix.

**Comment by tumba25** [comment]
Yes, you use Windows. And on Win I can reproduce that.
Your fix takes care of that. Thanks.
I'll push the fix soonish.
