### ISSUE TITLE
Directory name missing letters

### ISSUE THREAD

**Issue by David-NF** [phpbb/quickinstall#44]
I'm using 1.2.1-RC1 since today, downloaded the master from here. There is some strange behavior, I give up a directory name like FriendsFoes but QI makes it like riendsoes. I made some other boards as well where QI missed/leaved some letters in the directory name.

**Comment by Skouat** [comment]
Hi,

[Line 433](https://github.com/phpbb/quickinstall/blob/master/includes/qi_functions.php#L433)
`$dbname = preg_replace('/[^A Za-z0-9-_]*/', '', $dbname);`
must be replaced with
`$dbname = preg_replace('/[^A-Za-z0-9-_]*/', '', $dbname);`
And maybe you could lowercase the $dbmane with `strtolower`

eg : `$dbname = strtolower(preg_replace('/[^A-Za-z0-9-_]*/', '', $dbname));`

**Comment by tumba25** [comment]
Think that a small hyphen can do that much. Thanks for reporting.
@Skouat Yes, I noticed. No need to lowercase letters. Uppercase is allowed in both directory and DB names.

**Comment by David-NF** [comment]
Such small thing, wow :O added the fix to my QI installation. Will test it later on when I need to install a board. Thanks for the fast response!
