### ISSUE TITLE
.git directories not deleted

### ISSUE THREAD

**Issue by 3D-I** [phpbb/quickinstall#51]
As per the title, the .git directories are not being deleted while using the "delete board" button.
Results in the board still present in the main page and also the DB related.

I.E.: "...boards/tpotm/ext/threedi/tpotm/.git/objects/pack/pack-10d5387e64..etc...."

Being I guess this Tool used mosly by developers should do that, IMHO.
I will look in the code if I can be of any help, when I get some spare time.

**Comment by 3D-I** [comment]
Should the DB still be there usually? Big doubt.

**Comment by 3D-I** [comment]
Perhaps has to do with the class recursive_dot_prefix_filter_iterator?

**Comment by Skouat** [comment]
Hi,

[Line 27](https://github.com/phpbb/quickinstall/blob/master/includes/functions_files.php#L27) in function_files.php seems to return a "permission denied" when `unlink()` try to delete git objects files.

**Comment by 3D-I** [comment]
https://github.com/phpbb/quickinstall/pull/53

Thanks.
