### ISSUE TITLE
Feature request - Board's start date

### ISSUE THREAD

**Issue by 3D-I** [phpbb/quickinstall#57]
If possible, to add the option to decide the board's start date and while being populated to _random_ fill the _user post time_ according to that.
Thanks.

**Comment by DavidIQ** [comment]
You should be able to set the board start date using the _Board config options_ section.  It would just be another line in the box:
```board_startdate;123456789```

The other part of your request might be doable from that and probably should be.  It appears that right now the post date/time is the same for every single post.  This randomizing could prove to be difficult though so we'll see.

**Comment by 3D-I** [comment]
Thanks, later on I will fork this into my local devs and see if I could help here, is very interesting.
Say I am creating an hall of fame for the TPOTM, it will take care to provide monthly stats since the board's startdate, indeed the Posters needs to have a different post_time at least. I do not have a live environment to backup in order to create an optimal development limbo.

**Comment by VSEphpbb** [comment]
@DavidIQ Posts in a topic do not all have the same time. They are posted 1 second apart from each other, so with time displayed like hh:mm it only appears the time is all the same. However, every post and every topic does have a unique timestamp.
https://github.com/phpbb/quickinstall/blob/master/includes/functions_populate.php#L355

I don't see any benefit to randomizing timestamps (or any way to make such a complicated thing work for such an edge case use), considering you have to deal with a random number of forums, topics and posts, the wildcard board start date, and still manage some semblance of sequentially ordering them among posts within topics, and topics within forums, and user reg dates, etc.

**Comment by 3D-I** [comment]
Maybe considering ie.:
boardstardate = 5 years ago
tot posts 1000
dividing those 1000 posts per the tot months

not really randomising, I admit I used the wrong word.

**Comment by 3D-I** [comment]
I guess all of the meyhem goes here, includes/functions_populate..

```
			// Estimate the number of posts created.
			// Or in reality, calculate the highest possible number and convert to seconds in the past.
			// If one of them is zero this would not be so nice.
			$replies	= ($this->num_replies_max) ? $this->num_replies_max : 1;
			$topics		= ($this->num_topics_max) ? $this->num_topics_max : 1;
			$forums		= ($this->num_forums) ? $this->num_forums : 1;

			$this->post_time	= time() - ($topics * $replies * $forums);
			$this->post_time	= ($this->post_time < 0) ? 0 : $this->post_time;

```

This line
`			$this->post_time	= time() - ($topics * $replies * $forums);`

I guess, not tried, we could add a magic against a config['board_startdate'] of some sort and try..

What at the present time it does is to start posting a post/topic every second in the past accordingly to a SUM of variables, since now(),

**Comment by Derky** [comment]
Thanks for your feature request but we've decided to not add this because we don't see added value for QuickInstall.
