### ISSUE TITLE
Error installing 3.2.0-b2 - /quickinstall/index.php?page=create

### ISSUE THREAD

**Issue by 3D-I** [phpbb/quickinstall#58]
[QI Debug] PHP Warning: in file C:/EasyPHP-DevServer-14.1VC11/data/localweb/quickinstall/includes/functions_install.php on line 166: file_get_contents(boards/302b2pl1/install/schemas/schema_data.sql): failed to open stream: No such file or directory
[QI Debug] PHP Notice: in file C:/EasyPHP-DevServer-14.1VC11/data/localweb/quickinstall/sources/phpBB3_alt/302b2-pl1/phpbb/textformatter/s9e/factory.php on line 491: Undefined index: attachment

Catchable fatal error: Argument 1 passed to phpbb\textformatter\s9e\factory::merge_templates() must be of the type array, null given, called in C:\EasyPHP-DevServer-14.1VC11\data\localweb\quickinstall\sources\phpBB3_alt\302b2-pl1\phpbb\textformatter\s9e\factory.php on line 491 and defined in C:\EasyPHP-DevServer-14.1VC11\data\localweb\quickinstall\sources\phpBB3_alt\302b2-pl1\phpbb\textformatter\s9e\factory.php on line 583

Note: i called 

> 302b2-pl1

 the source for my conveniences. 
it is a **3.2.0-b2** source (download package).

I am using the release 1.2.2 - (https://github.com/phpbb/quickinstall/releases/latest)

**Comment by DavidIQ** [comment]
QI was tested with 3.2 for the last release and was found to have been working so this is a strange error.  Not sure where you got your 3.2.0-b2 from but the schema file does indeed exist in 3.2:
https://github.com/phpbb/phpbb/tree/3.2.x/phpBB/install/schemas

Are you missing schema_data.sql from your source files?

**Comment by 3D-I** [comment]
My fault David, thank you. I shouldn't work on my projects when I am tired.
The issue was I renamed the install folder. Apologies.

BTW, thanks everybody here for the great work.

**Comment by DavidIQ** [comment]
No problem.  Thanks for getting back to us.
