### ISSUE TITLE
NRUsers - INACTIVE - are missing

### ISSUE THREAD

**Issue by 3D-I** [phpbb/quickinstall#59]
I have never been able to get some NRU into my multiple installations (3.0, 3.1, 3.2 now too).

I sat ie.: 10 users total (with admins and mods) but 3 NRU, always.
edit: those 3 are in NRU but I do not have INACTIVE users.

Any clue? Has been also this tested?

**Comment by VSEphpbb** [comment]
It adds users to the Newly Registered User group. You can set how many users you want added to this group in the settings.

QI does not create inactive users...nor does Newly Registered Users need be considered inactive users.

Once you have your board up, if you need to test something with inactive users, you can go to the ACP and de-activate any users there, under the Quick Tools drop down.

**Comment by 3D-I** [comment]
Anyway the set NRU per default and thus the post limit are set to no, is this the normal desired behaviour?

**Comment by VSEphpbb** [comment]
Yes.

If you're trying to accomplish something specific with New Reg Users, then you can create some users on your own, add them to the group, and make sure they have all the desired traits you need them to have.

The QI is built just to provide a quick install of phpBB, populated with data if desired. But in the end, it's a test board and once it's up and running, it's your playground to do with what you want and/or need for your unique development needs. The data it is populated with has no meaning, it's just so you have a bunch of posts, topics, forums and users already in place, as a starting point for development with some data on board.

**Comment by 3D-I** [comment]
Different points of view man, one thingh is what this tool has been in the past made (ideas based on a past version/s) for and the other side of the coin could be what we would like it to be now a days.

Look forward.
