### ISSUE TITLE
Error installing 3.2.0-RC1

### ISSUE THREAD

**Issue by 3D-I** [phpbb/quickinstall#60]
> [QI Debug] PHP Notice: in file C:/easyphp161/eds-www/QI/includes/functions_populate.php on line 531: Undefined index: TEST_FORUM_NAME
> [QI Debug] PHP Notice: in file /includes/message_parser.php on line 1198: Undefined index: TOO_FEW_CHARS
> [QI Debug] PHP Notice: in file /includes/acp/acp_forums.php on line 970: Undefined index: FORUM_NAME_EMPTY

```
BACKTRACE

FILE: [ROOT]/includes/functions_populate.php
LINE: 583
CALL: trigger_error()

FILE: [ROOT]/includes/functions_populate.php
LINE: 515
CALL: populate->_create_forums()

FILE: [ROOT]/includes/functions_populate.php
LINE: 172
CALL: populate->create_forums()

FILE: [ROOT]/modules/qi_create.php
LINE: 840
CALL: populate->populate()

FILE: [ROOT]/includes/functions_module.php
LINE: 52
CALL: qi_create->__construct()

FILE: [ROOT]/index.php
LINE: 296
CALL: module_handler->load()
```

**Comment by 3D-I** [comment]
![qi-populate-320rc1-1](https://cloud.githubusercontent.com/assets/480857/15359703/cf3e7068-1d0a-11e6-9196-7e653ebe9b5d.png)

**Comment by DavidIQ** [comment]
Not sure what the picture is for?

**Comment by 3D-I** [comment]
the module qi_create.php, called by the bactrace says

```
		// Add some random users and posts. Revisit.
		if ($settings->get_config('populate', false))
		{
			include($quickinstall_path . 'includes/functions_populate.' . $phpEx);
			new populate();
		}
```
that's the reason of the pic, settings are ok, I did install a 320-b2 right 10 minutes before and everything went fine..

**Comment by VSEphpbb** [comment]
This is just a PHP notice. 

This is also not reproducible.

You may have messed up some lang files, or are using an incomplete translation.

**Comment by 3D-I** [comment]
I work only with original files and **ONLY** in English.

phpBb 3.2.0-c1 from here
[](https://download.phpbb.com/pub/release/3.2/unstable/3.2.0-RC1/)
and QI from here
[https://github.com/phpbb/quickinstall/releases/tag/v1.2.2](url)

**Comment by VSEphpbb** [comment]
Oh OK i see now.

@Nicofuma Any ideas what changed in 3.2.0 beta to RC that may be causing this?
