### ISSUE TITLE
No connection to postgreSQL database

### ISSUE THREAD

**Issue by Lady-G** [phpbb/quickinstall#75]
As described in [Broken install with postgreSQL, unable to view documents](https://www.phpbb.com/customise/db/official_tool/phpbb3_quickinstall/support/topic/174756?p=548166#p548166 "Broken install with postgreSQL, unable to view documents"), no connection with postgreSQL can be established.

My localhost environment is running postgreSQL with phpBB 3.1.10 and 3.2.0, there are no issues. This problem is isolated to quickinstall.

Here is the stack trace:
```
The pgsql dbms is either not supported, or the php extension for it could not be loaded.

BACKTRACE

FILE: [ROOT]/includes/qi_functions.php
LINE: 533
CALL: trigger_error()

FILE: [ROOT]/modules/qi_manage.php
LINE: 75
CALL: db_connect()

FILE: [ROOT]/includes/functions_module.php
LINE: 52
CALL: qi_manage->__construct()

FILE: [ROOT]/index.php
LINE: 296
CALL: module_handler->load()
```
Environment:
```
PostgreSQL 9.5.6 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1), 64-bit
PHP Version 5.6.29
```

**Comment by DavidIQ** [comment]
What does your config.php file look like for the qi instance vs the one that actually works?

**Comment by Lady-G** [comment]
The qi instance looks like this (user and password as placeholders):
```
<?php
// phpBB 3.2.x auto-generated configuration file
// Do not change anything in this file!
$dbhost = 'localhost';
$dbport = '';
$dbname = 'qi_phpbb';
$dbuser = 'example';
$dbpasswd = 'example';
$table_prefix = 'phpbb_';
$dbms = 'phpbb\\db\\driver\\pgsql';
$acm_type = 'phpbb\\cache\\driver\\file';
$phpbb_adm_relative_path = 'adm/';

@define('PHPBB_INSTALLED', true);
@define('DEBUG', true);
@define('PHPBB_ENVIRONMENT', 'production');
//@define('DEBUG_CONTAINER', true);
@define('PHPBB_DISPLAY_LOAD_TIME', true);
```
My phpBB 3.2.0 production test installation looks like this. There is no database prefix.
```
<?php
// phpBB 3.0.x auto-generated configuration file
// Do not change anything in this file!
$dbms = 'postgres';
$dbhost = 'localhost';
$dbport = '';
$dbname = 'example';
$dbuser = 'example';
$dbpasswd = '';
$table_prefix = '';
$acm_type = 'memcache';
$load_extensions = '';
@define('PHPBB_DISPLAY_LOAD_TIME', true);

@define('PHPBB_INSTALLED', true);
// @define('DEBUG', true);
// @define('DEBUG_EXTRA', true);
?>
```

**Comment by DavidIQ** [comment]
Can you try changing the word _pgsql_ in the qi instance to _postgres_ and see if that makes it work?

**Comment by Lady-G** [comment]
The connection is working, as I now get a postgres stack trace. The sequence I followed:

1. In postgreSQL, create database qi_phpbb.
2. Run quickinstall, source code is created.
3. Edit config.php as described below.

The instance is connecting to an empty database (no tables were created).

I modified the qi instance of $dbms as:
```
<?php
// phpBB 3.2.x auto-generated configuration file
// Do not change anything in this file!
$dbhost = 'localhost';
$dbport = '';
$dbname = 'qi_phpbb';
$dbuser = 'example';
$dbpasswd = 'example';
$table_prefix = 'phpbb_';
$dbms = 'phpbb\\db\\driver\\postgres';
$acm_type = 'phpbb\\cache\\driver\\file';
$phpbb_adm_relative_path = 'adm/';

@define('PHPBB_INSTALLED', true);
@define('DEBUG', true);
@define('PHPBB_ENVIRONMENT', 'production');
//@define('DEBUG_CONTAINER', true);
@define('PHPBB_DISPLAY_LOAD_TIME', true);
```
The stack trace:
```
General Error
SQL ERROR [ postgres ]

ERROR: relation "phpbb_config" does not exist LINE 2: FROM phpbb_config ^ []

SQL

SELECT config_name, config_value, is_dynamic FROM phpbb_config

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/postgres.php
LINE: 194
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\postgres->sql_query()

FILE: [ROOT]/phpbb/config/db.php
LINE: 71
CALL: phpbb\db\driver\factory->sql_query()

FILE: (not given by php)
LINE: (not given by php)
CALL: phpbb\config\db->__construct()

FILE: [ROOT]/vendor/symfony/dependency-injection/ContainerBuilder.php
LINE: 928
CALL: ReflectionClass->newInstanceArgs()

FILE: [ROOT]/vendor/symfony/dependency-injection/ContainerBuilder.php
LINE: 468
CALL: Symfony\Component\DependencyInjection\ContainerBuilder->createService()

FILE: [ROOT]/vendor/symfony/dependency-injection/ContainerBuilder.php
LINE: 985
CALL: Symfony\Component\DependencyInjection\ContainerBuilder->get()

FILE: [ROOT]/vendor/symfony/dependency-injection/ContainerBuilder.php
LINE: 982
CALL: Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices()

FILE: [ROOT]/vendor/symfony/dependency-injection/ContainerBuilder.php
LINE: 897
CALL: Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices()

FILE: [ROOT]/vendor/symfony/dependency-injection/ContainerBuilder.php
LINE: 468
CALL: Symfony\Component\DependencyInjection\ContainerBuilder->createService()

FILE: [ROOT]/phpbb/di/container_builder.php
LINE: 418
CALL: Symfony\Component\DependencyInjection\ContainerBuilder->get()

FILE: [ROOT]/phpbb/di/container_builder.php
LINE: 158
CALL: phpbb\di\container_builder->load_extensions()

FILE: [ROOT]/common.php
LINE: 115
CALL: phpbb\di\container_builder->get_container()

FILE: [ROOT]/index.php
LINE: 23
CALL: include('[ROOT]/common.php')
```

**Comment by 3D-I** [comment]
Could you try this
https://github.com/phpbb/quickinstall/pull/76

and install a new board the usual way?

**Comment by Lady-G** [comment]
I first tried [#76](https://github.com/phpbb/quickinstall/pull/76 "#76"), but was not offered a postgresql choice in the profile tab. VSEphpbb's  [ Fix postgresql failures #77 ](https://github.com/phpbb/quickinstall/issues/77 " Fix postgresql failures #77 ") fixed the profile issue and I was able to proceed.

```
git clone https://github.com/phpbb/quickinstall.git
git pull origin pull/77/head
```

The install was not successful. First, I created a database as qi_phpbb. Installation stopped because the database already existed. `The database "qi_phpbb" already exists.` 

Next, I dropped qi_phpBB to start clean. Installation stopped because it was unable to create the database. Catch-22.

_Board database and directory name:*_ entry contains _phpbb_.
```
General Error
SQL ERROR [ ]

Errno 2: pg_connect(): Unable to connect to PostgreSQL server: FATAL: database "qi_phpbb" does not exist at [ROOT]/phpbb/db/driver/postgres.php line 98 []

BACKTRACE

FILE: [ROOT]/sources/phpBB3/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/sources/phpBB3/phpbb/db/driver/postgres.php
LINE: 113
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/includes/db/31/postgres.php
LINE: 33
CALL: phpbb\db\driver\postgres->sql_connect()

FILE: [ROOT]/modules/qi_create.php
LINE: 308
CALL: dbal_postgres_qi->sql_connect()

FILE: [ROOT]/includes/functions_module.php
LINE: 52
CALL: qi_create->__construct()

FILE: [ROOT]/index.php
LINE: 296
CALL: module_handler->load()
```
The board's config.php (user and password as placeholders):
```
<?php
// phpBB 3.2.x auto-generated configuration file
// Do not change anything in this file!
$dbhost = 'localhost';
$dbport = '';
$dbname = 'qi_phpbb';
$dbuser = 'example';
$dbpasswd = 'example';
$table_prefix = 'phpbb_';
$dbms = 'phpbb\\db\\driver\\postgres';
$acm_type = 'phpbb\\cache\\driver\\file';
$phpbb_adm_relative_path = 'adm/';

@define('PHPBB_INSTALLED', true);
@define('DEBUG', true);
@define('PHPBB_ENVIRONMENT', 'production');
//@define('DEBUG_CONTAINER', true);
@define('PHPBB_DISPLAY_LOAD_TIME', true);
```

**Comment by VSEphpbb** [comment]
You are not pulling in the changes because they have not been merged yet.

**Comment by Lady-G** [comment]
The changes are merged locally. Is it possible I missed the last (3rd) commit)? We may be close in the time of day I tested vs. your commits. I tried this again and see an additional file changed in [Fix postgresql failures #77](https://github.com/phpbb/quickinstall/pull/77 "Fix postgresql failures #77"). My localhost git activity shows the merge being performed. The file changes match the pull request.

```
#git clone https://github.com/phpbb/quickinstall.git

Cloning into 'quickinstall'...
remote: Counting objects: 3671, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 3671 (delta 1), reused 0 (delta 0), pack-reused 3666
Receiving objects: 100% (3671/3671), 2.91 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1848/1848), done.
Checking connectivity... done.
#cd quickinstall/
#git pull origin pull/77/head
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 14 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.
From https://github.com/phpbb/quickinstall
 * branch            refs/pull/77/head -> FETCH_HEAD
Merge made by the 'recursive' strategy.
 includes/functions_install.php |  5 +++--
 includes/qi_functions.php      | 37 +++++++++++++++++++++++++++----------
 modules/qi_create.php          | 11 ++++++++++-
 3 files changed, 40 insertions(+), 13 deletions(-)
```
Success! I was able to create a populated postgreSQL board. However, I needed to create the database first or the result was a FATAL stack trace as described earlier.

This pull request also fixed my document display errors as described in [Broken install with postgreSQL, unable to view documents](https://www.phpbb.com/customise/db/official_tool/phpbb3_quickinstall/support/topic/174756?p=548166#p548166 "Broken install with postgreSQL, unable to view documents")

**Comment by VSEphpbb** [comment]
You are not getting the latest changes because the latest changes only exist on my repository and all of your polls are coming from the PHPBB repository. That is why you still have to create a database and all that other stuff which does not need to happen after this PR gets merged. Please wait for this PR to be merged

**Comment by VSEphpbb** [comment]
You do not have to create a database. It works just fine once this PR is merged. Please wait for it to be merged. As mentioned in the PR, it works now as expected in two completely different environments.

If you had a fatal error it may because you broke your postgresql database by deleting the default postgres DB that MUST always be present in a postgresql server by default.

**Comment by VSEphpbb** [comment]
Oh I see. The current changes may have been deleting the default postgres db when deleting boards. Some more fixes may be on the way for that.

**Comment by Lady-G** [comment]
Thank you, your explanation helped me understand this problem.

The default postgres DB was not deleted. The error was my fault, as I forgot to add permissions of my database user to create a database. `alter user dbUser CREATEDB;` 

I have tested the merged changes and everything is working.
