### ISSUE TITLE
[1.3.x] Lang key "INSTALL_STYLES_EXPLAIN" bad directory reference.

### ISSUE THREAD

**Issue by Skouat** [phpbb/quickinstall#87]
Hi,

The directory `sources/styles/` quoted in the lang key [INSTALL_STYLES_EXPLAIN](https://github.com/phpbb/quickinstall/blob/1.3.0-RC1/language/en/qi.php#L159) doesn't exist.

Does it should be `sources/phpBB3/styles/`?

**Comment by VSEphpbb** [comment]
f2fe797c31cb177e8fc817fc38f4af4169e23eab
