### ISSUE TITLE
Distinct use of the extra folder

### ISSUE THREAD

**Issue by 3D-I** [phpbb/quickinstall#93]
Hello, first off thx for the new release.. looks really modern/nice and fast. 👍 

One question: I use the extra folder to add extensions to the newly created boards as usual 
(see: extra/ext/... extensions here ..)

Is it already available an option/shortcut which allows me to use that folder based on the phpBB version?

See.. 
(extra/language/ ... extra langs for 3.1/3.2)
or
(extra/styles/ .. extra styles for 3.1/3.2)

**Comment by VSEphpbb** [comment]
Please us the support forum linked to from the readme.
