### ISSUE TITLE
General Error when attempting to instal PHPBB 3.2.2 through EasyPHP

### ISSUE THREAD

**Issue by RegalSeagull** [phpbb/quickinstall#99]
First time trying anything like is.
Attempting to create a board and keep getting this.

General Error
SQL ERROR [ mysql_41 ]

Access denied for user 'AdminQI'@'localhost' (using password: YES) [1045]

BACKTRACE

FILE: [ROOT]/sources/phpBB3/phpbb/db/driver/driver.php
LINE: 996
CALL: trigger_error()

FILE: [ROOT]/includes/db/31/mysqli.php
LINE: 46
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/includes/qi_functions.php
LINE: 561
CALL: dbal_mysqli_qi->sql_connect()

FILE: [ROOT]/modules/qi_create.php
LINE: 239
CALL: db_connect()

FILE: [ROOT]/includes/functions_module.php
LINE: 52
CALL: qi_create->__construct()

FILE: [ROOT]/index.php
LINE: 296
CALL: module_handler->load()

**Comment by DavidIQ** [comment]
And that user exists in your MySQL instance?

**Comment by RegalSeagull** [comment]
Wow that was fast! On QuickInstall you mean? I have it like this in my profile:

![screenshot_2018-08-14 profiles phpbb quickinstall](https://user-images.githubusercontent.com/42345225/44031968-c739b368-9f59-11e8-8242-e8213e1cc26b.png)

**Comment by DavidIQ** [comment]
No. The user has to exist in MySQL. QuickInstall cannot do that for you.

**Comment by RegalSeagull** [comment]
OH. That makes more sense. Like this?

![screenshot_2018-08-14 127 0 0 1 127 0 0 1 phpmyadmin 4 7 0](https://user-images.githubusercontent.com/42345225/44032202-8da39334-9f5a-11e8-98ba-503b712e450d.png)

**Comment by DavidIQ** [comment]
Yes, exactly. That should allow you to continue with the QI process.

**Comment by RegalSeagull** [comment]
Aha! Thank you!!

Making my own user didn't work so I instead added the user as 'root' with no password, and it now functions! Thanks so much for your quick responses.

**Comment by ivellios1988** [comment]
I just encountered a similar issue with running phpBB in EasyPHP. Turns out you just can't use passwords in your databases, I must set the password to empty in config.php to make my forum work as expected. Changing passwords in phpmyadmin results in nothing, no password is set for any database user
